### ISSUE TITLE
Investigate adding a CI plugin to github

### ISSUE THREAD

**Issue by JordanPaoletti** [JordanPaoletti/Conflict_Checker#24]
Github complains about not having CI setup to do some checking in pull requests. This makes me want CI. Travis CI is free for opensource project. Seems like its worth a shot!

**Comment by Ferrin13** [comment]
@JordanPaoletti Apparently only the repository owner can activate Travis on a project. Once you do that I should be able to configure it. https://docs.travis-ci.com/user/tutorial/
